
CREATE SEQUENCE UNIT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE UNIT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
SELECT UNIT_SEQ.nextval FROM dual;
DROP SEQUENCE UNIT_SEQ;

SELECT * FROM ALL_SEQUENCES;
SELECT * FROM USER_SEQUENCES;

-- cambiar valor siguiente

ALTER SEQUENCE AUDIT_SEQ INCREMENT BY 168;
SELECT AUDIT_SEQ.nextval FROM dual;
ALTER SEQUENCE AUDIT_SEQ INCREMENT BY 1;


---------------------------

CREATE SEQUENCE AUDIT_SEQ START WITH 39 INCREMENT BY 1;
CREATE SEQUENCE AUDIT_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 97 CACHE 20 NOORDER  NOCYCLE ;
DROP SEQUENCE ANUNCIO_SEQ;
CREATE SEQUENCE ANUNCIO_SEQ START WITH 39 INCREMENT BY 1;

--------------

ALTER SEQUENCE serial INCREMENT BY 400;
SELECT serial.NEXTVAL FROM dual;
ALTER SEQUENCE serial INCREMENT BY 1;

--------------

DROP SEQUENCE AUDIT_SEQ;
CREATE SEQUENCE AUDIT_SEQ START WITH 1 INCREMENT BY 1;
