alter database datafile 'C:\TOOLS\ORACLEXE\APP\ORACLE\ORADATA\XE\SYSTEM.DBF' autoextend on next 128m maxsize 8192m;


CREATE TABLESPACE tbs_01 DATAFILE 'tbs_f2.dat' SIZE 40M ONLINE;

ALTER TABLE ACTA MOVE TABLESPACE TBS_01;
